version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: local-life-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: local-life-service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - local-life-network
    command: mongod --auth --bind_ip_all

  mongodb-express:
    image: mongo-express:1.0.0
    container_name: local-life-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - local-life-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  local-life-network:
    driver: bridge
